### ISSUE TITLE
HA 2024.3.0 breaks with "Setup failed for 'persistent_notification': Invalid config"

### ISSUE THREAD

**Issue by sandersr** [arturpragacz/hass-cc-early-loader#1]
Release 2024.3.0 breaks on this component with the following error message:

ERROR (MainThread) [homeassistant.config] Error importing config platform persistent_notification: No module named 'custom_components.persistent_notification.config'
ERROR (MainThread) [homeassistant.setup] Setup failed for 'persistent_notification': Invalid config.
ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'persistent_notification': Integration failed to initialize.

**Comment by arturpragacz** [comment]
Try the updated version. Let me know if it works.

**Comment by sandersr** [comment]
Thank you for resolving it so quickly! Everything is working as expected now!
